name: Release

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Release
        uses: gravity-ui/release-action@v2
        with:
          github-token: ${{ secrets.GRAVITY_UI_BOT_GITHUB_TOKEN }}
          node-version: '24'
